AWSTemplateFormatVersion: 2010-09-09
Description: "Service Catalog product to create an Organizational Unit (OU)"
Parameters:
  OUName:
    Type: String
    Description: "Name of the new Organizational Unit"
    AllowedPattern: ".+"
  ParentOU:
    Type: String
    Description: "Parent OU ID (e.g., 'r-xxxx' for Root or 'ou-xxxx-yyyy' for nested OU)"
Resources:
  CreateOUCustomResource:
    Type: Custom::CreateOU
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:918116814056:function:CreateOU
      OUName: !Ref OUName
      ParentId: !Ref ParentOU
Outputs:
  OrganizationalUnitId:
    Description: "The newly created Organizational Unit ID"
    Value: !GetAtt CreateOUCustomResource.OUId
