security_email = "huzphotos1303+testct2@gmail.com"
shared_email   = "huzphotos1303+testctshared@gmail.com"
test_email = "huzphotos1303+testemail@gmail.com"
production_email = "huzphotos1303+testctproduction@gmail.com"
dev_email = "huzphotos1303+testctdev@gmail.com"
account_factory_product_id="prod-xmve3rknwimb6"